In [29]:
import numpy as np

In [30]:
np.random.seed(10)
X=np.random.randint(100,size=(4,4))
print(X)

[[ 9 15 64 28]
 [89 93 29  8]
 [73  0 40 36]
 [16 11 54 88]]


In [31]:

XBool=X%2==0
print(XBool)

[[False False  True  True]
 [False False False  True]
 [False  True  True  True]
 [ True False  True  True]]


In [32]:
parX=X[XBool]
print(parX)

[64 28  8  0 40 36 16 54 88]


In [33]:
media=np.mean(X)
print("media:",media)
Xgrandes=X>media
print(Xgrandes)
mediaX=X[Xgrandes]
print(mediaX)

media: 40.8125
[[False False  True False]
 [ True  True False False]
 [ True False False False]
 [False False  True  True]]
[64 89 93 73 54 88]


In [34]:
print(X)

[[ 9 15 64 28]
 [89 93 29  8]
 [73  0 40 36]
 [16 11 54 88]]


In [35]:
#Veamos cuantos hay mmenores que la media
np.count_nonzero(X<media)

10

In [36]:
#O bien obtenerlos de la siguiente manera
np.sum(X<media)

10

In [37]:
#Supongamos que deseamos saber cuantos hay en cada fila
np.sum(X<media,axis=1)

array([3, 2, 3, 2])

In [38]:
#Ahora en cada columna
np.sum(X<media,axis=0)

array([2, 3, 2, 3])

In [39]:
desviStd=np.std(X)
np.any(X>media+desviStd)

True

In [40]:
np.all(X>media+desviStd)

False

In [41]:
###Ahora si, regresemos al ejercicio que estabamos haciendo hace un ratito
import pandas as pd
data = pd.read_csv('data/altura_presidentes_EEUU.csv')
alturas = np.array(data['altura(cm)'])
print(alturas)


filtro_low=alturas<np.mean(alturas)
lowHeights=alturas[filtro_low]
print(lowHeights)
print(len(lowHeights))

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]
[170 163 171 168 173 173 173 175 178 178 173 174 168 170 178 178 175 179
 177]
19


**Esta parte solo la veremos si el tiempo lo permite**

**Esta parte solo la veremos si el tiempo lo permite**

**Esta parte solo la veremos si el tiempo lo permite**

**Esta parte solo la veremos si el tiempo lo permite**


In [42]:

## Trabajemos ahora con los índices
## Trabajemos ahora con los índices
## Trabajemos ahora con los índices
## Trabajemos ahora con los índices
## Trabajemos ahora con los índices
## Trabajemos ahora con los índices
## Trabajemos ahora con los índices
## Trabajemos ahora con los índices

In [43]:
X=np.random.randint(10,size=10)
print(X)

[1 8 4 1 3 6 5 3 9 6]


In [44]:
XImp=[X[1],X[3],X[5],X[7],X[9]]
print(XImp)

[8, 1, 6, 3, 6]


In [45]:
imparIndex=[1,3,5,7,9]
XImp2=X[imparIndex]
print(XImp2)

[8 1 6 3 6]


In [46]:
#Y si el arreglo fuera de tamaño 100
X=np.random.randint(10,size=100)
XInt=np.arange(start=1,stop=99,step=2)
print(XInt)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97]


In [47]:
print(X)
print(X[XInt])

[9 1 9 4 2 6 7 8 8 9 2 0 6 7 8 1 7 1 4 0 8 5 4 7 8 8 2 6 2 8 8 6 6 5 6 0 0
 6 9 1 8 9 1 2 8 9 9 5 0 2 7 3 0 4 2 0 3 3 1 2 5 9 0 1 0 1 9 0 9 2 1 1 0 0
 5 9 0 4 6 6 0 2 3 3 2 6 0 5 1 3 6 5 5 1 8 0 5 9 8 5]
[1 4 6 8 9 0 7 1 1 0 5 7 8 6 8 6 5 0 6 1 9 2 9 5 2 3 4 0 3 2 9 1 1 0 2 1 0
 9 4 6 2 3 6 5 3 5 1 0 9]


In [48]:
#Ejemplo 2
X = np.arange(25).reshape((5, 5))
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [49]:
fila=np.array([1,3,2])
columna=np.array([0,2,4])
print(X[fila,columna])

[ 5 17 14]


In [50]:
#Combinando índices
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [51]:
X[3,[3,1,4]]

array([18, 16, 19])

In [102]:
X[2:,[3,1,4]]

array([[13, 11, 14],
       [18, 16, 19],
       [23, 21, 24]])

In [103]:
#Asi como podemos filtrar valores, también podemos cambiar los valores
X[2:,[3,1,4]]=0

In [106]:
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10  0 12  0  0]
 [15  0 17  0  0]
 [20  0 22  0  0]]


In [108]:
Y=np.copy(X)
print(Y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [109]:
#Ahora asignemos a los 0's de la columna número 1 incrementemos el valor 1 
Y[2:,[3,1,4]]=0
print(Y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10  0 12  0  0]
 [15  0 17  0  0]
 [20  0 22  0  0]]


In [110]:
#Ahora incrementemos el valor 1 a los elementos en la columna 1
Y[2:,[1]]=Y[2:,[1]]+1
print(Y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10  1 12  0  0]
 [15  1 17  0  0]
 [20  1 22  0  0]]


In [111]:
#Ahora incrementemos en dos el valor de la fila 2 y columnas 3 y 4
Y[2,[3,4]]=2
print(Y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10  1 12  2  2]
 [15  1 17  0  0]
 [20  1 22  0  0]]


In [ ]:
###EJERCICIOS
###EJERCICIOS
###EJERCICIOS
###EJERCICIOS
###EJERCICIOS
###EJERCICIOS
###EJERCICIOS
###EJERCICIOS
###EJERCICIOS
###EJERCICIOS
###EJERCICIOS
###EJERCICIOS
###EJERCICIOS
###EJERCICIOS
###EJERCICIOS
###EJERCICIOS
###EJERCICIOS
###EJERCICIOS
###EJERCICIOS
###EJERCICIOS

In [114]:
M_Ex1=np.random.randint(-100,100,size=16).reshape(4,4)
print(M_Ex1)

[[  66   65   87    3]
 [ -80   59  -11   24]
 [-100   -4  -75  -37]
 [ -41  -98  -70  -83]]


In [115]:
suma=np.sum(M_Ex1)
print(suma)

-295


In [116]:
suma_1=np.sum(M_Ex1[0])
print(suma_1)

221


In [118]:
suma_1=np.sum(M_Ex1[:,0])
print(suma_1)

-155


In [119]:
media_1=np.mean(M_Ex1[:,3])
print(media_1)

-23.25


In [124]:
filtro=M_Ex1>media_1
print(filtro)

[[ True  True  True  True]
 [False  True  True  True]
 [False  True False False]
 [False False False False]]


In [126]:
M_Ex2=M_Ex1[filtro]
print(M_Ex2)

[ 66  65  87   3  59 -11  24  -4]
