In [1]:

import numpy as np
#Ex 1
M1=np.random.randint(-100,100,size=9).reshape(3,3)

In [2]:
M1

array([[-28, -17, -68],
       [ 28,  91,  88],
       [ 65,  -9, -20]])

In [3]:
#Ex 2
M2=abs(M1)
print(M2)

[[28 17 68]
 [28 91 88]
 [65  9 20]]


In [4]:
#Ex 3
suma_todos=np.add.reduce(M1)
suma_absolutos=np.add.reduce(M2)
print(suma_todos)
print(suma_absolutos)
print(np.add.reduce(suma_todos))
print(np.add.reduce(suma_absolutos))

[65 65  0]
[121 117 176]
130
414


In [6]:
#Ex 4
def divisores(x):
    suma=0
    auxArray=[i for i in range(1,x+1) if x%i==0]
    cuantos=len(auxArray)
    return cuantos


In [9]:

M4=np.zeros(9).reshape(3,3)
print("Matriz M2:\n",M2)
for i in range(0,M2.ndim+1):
    M4[i]=np.array(list(map(lambda a:divisores(a),M2[i])))
M4=M4.astype(int)
print(M4)

Matriz M2:
 [[28 17 68]
 [28 91 88]
 [65  9 20]]
[[6 2 6]
 [6 4 8]
 [4 3 6]]
