In [27]:
import numpy as np
np.random.seed(0)

valores=np.random.randint(1,10,size=10)

In [28]:
print(valores)

[6 1 4 4 8 4 6 3 5 8]


In [29]:
#Aplicar la misma función a un arreglo NP
valoresmasdos=np.add(valores,2)
print(valoresmasdos)

[ 8  3  6  6 10  6  8  5  7 10]


In [30]:
x=np.random.randint(10,size=5)
print(x)

[6 8 8 1 6]


In [31]:
y=x+5
print(y)

[11 13 13  6 11]


In [32]:
y=x-5
print(y)

[ 1  3  3 -4  1]


In [33]:
y=x//2
print(y)

[3 4 4 0 3]


In [34]:
import math
y=abs(x)
print(y)

[6 8 8 1 6]


In [35]:
y=np.log(x)
print(y)

[1.79175947 2.07944154 2.07944154 0.         1.79175947]


In [36]:
ysin=np.sin(x)
print("x:",x)
print("Funcion seno:",ysin)

x: [6 8 8 1 6]
Funcion seno: [-0.2794155   0.98935825  0.98935825  0.84147098 -0.2794155 ]


In [37]:
#Funciones de agregación
x=np.arange(1,6)
y=np.add.reduce(x)
print(y)

15


In [38]:
y=np.multiply.reduce(x)
print(y)

120


In [41]:
y=np.add.accumulate(x)
print(x)
print(y)

[1 2 3 4 5]
[ 1  3  6 10 15]


In [42]:
y=np.multiply.accumulate(x)
print(y)

[  1   2   6  24 120]


In [43]:
#Hagamos una función que dado un arreglo de enteros positivos [0..10], imprima el factorial del entero correspondiente
def factorial(x):
    if x<2:
        return 1
    else:
        return x*factorial(x-1)

y=np.array(list(map(lambda a:factorial(a),x)))
print(y)

[  1   2   6  24 120]


In [44]:
M=np.random.randint(9,size=(3,3))
print(M)

[[7 7 8]
 [1 5 8]
 [4 3 0]]


In [45]:
X=np.zeros(9).reshape(3,3)
for i in range(3):
    X[i]=np.array(list(map(lambda a:factorial(a),M[i])))
print(X)

[[5.040e+03 5.040e+03 4.032e+04]
 [1.000e+00 1.200e+02 4.032e+04]
 [2.400e+01 6.000e+00 1.000e+00]]
