In [55]:
import numpy as np

L=np.random.randint(100,size=20)
print(L)

[55 21 55 49 72 86 69 74 99 76 44 88 32 72  6 93  7 62 55 29]


In [56]:
def minElemento(L):
    xMin=L[0]
    for i in range(1,len(L)):
        if L[i]<xMin:
            xMin=L[i]
    return xMin

minV=minElemento(L)
print(minV)

minV2=np.min(L)
print(minV2)


6
6


In [57]:

addL=np.sum(L)
print(addL)

1144


In [58]:
print(np.min(L),np.max(L),np.sum(L))

6 99 1144


In [59]:
#Igual se puede hacer sobre arreglos
MA=np.random.randint(100,size=(3,3))
print(MA)

[[14 41 69]
 [95  4  1]
 [66 45 31]]


In [60]:
minMA=np.min(MA)
print(minMA)

1


In [61]:
minMAbyColumn=np.min(MA,axis=0)
print(minMAbyColumn)

[14  4  1]


In [62]:
minMAbyRow=np.min(MA,axis=1)
print(minMAbyRow)

[14  1 31]


In [63]:
minMA

1

In [64]:
import pandas as pd
data = pd.read_csv('data/altura_presidentes_EEUU.csv')
print(data)

    orden                  nombre  altura(cm)
0       1       George Washington         189
1       2              John Adams         170
2       3        Thomas Jefferson         189
3       4           James Madison         163
4       5            James Monroe         183
5       6       John Quincy Adams         171
6       7          Andrew Jackson         185
7       8        Martin Van Buren         168
8       9  William Henry Harrison         173
9      10              John Tyler         183
10     11           James K. Polk         173
11     12          Zachary Taylor         173
12     13        Millard Fillmore         175
13     14         Franklin Pierce         178
14     15          James Buchanan         183
15     16         Abraham Lincoln         193
16     17          Andrew Johnson         178
17     18        Ulysses S. Grant         173
18     19     Rutherford B. Hayes         174
19     20       James A. Garfield         183
20     21       Chester A. Arthur 

In [65]:
alturas = np.array(data['altura(cm)'])
print(heights)

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]


In [66]:
mediaAlturas=np.mean(alturas)
stdAlturas=alturas.std()
minAlturas=alturas.min()
maxAlturas=np.max(alturas)
medianaAlturas=np.median(alturas)

print("Valor medio:       ", mediaAlturas)
print("Desviación Estandar:", stdAlturas)
print("Minima Altura:    ", minAlturas)
print("Maxima Altura:    ", maxAlturas)
print("Mediana alturas:", medianaAlturas)



Valor medio:        179.73809523809524
Desviación Estandar: 6.931843442745892
Minima Altura:     163
Maxima Altura:     193
Mediana alturas: 182.0


In [69]:
#Operaciones que involucran mas de un vector o matriz

MA=np.random.randint(100,size=(3,3))
MB=np.random.randint(100,size=(3,3))
print(MA)
print(MB)

[[33 31 21]
 [17 46 29]
 [20 92  0]]
[[54 53 90]
 [90 90 25]
 [73 50 75]]


In [70]:
def sumaMatrices(ma,mb):
    newMatriz=np.zeros((3,3))
    rows,columns=ma.shape
    for i in range(0,rows):
        for j in range(0,columns):
            newMatriz[i,j]=ma[i,j]+mb[i,j]
    return newMatriz

In [71]:
print(sumaMatrices(MA,MB))

[[ 87.  84. 111.]
 [107. 136.  54.]
 [ 93. 142.  75.]]


In [72]:
print(MA+MB)

[[ 87  84 111]
 [107 136  54]
 [ 93 142  75]]


In [73]:
#Será que la multiplicacion tambien funcione?
print(MA*MB)

[[1782 1643 1890]
 [1530 4140  725]
 [1460 4600    0]]


In [74]:
#Hagamos un ejemplo con los elementos de una submatriz
M = np.random.randint(100,size=(10, 3))
print(M)

[[ 5 18 43]
 [51 34 50]
 [18 70 52]
 [67 12 77]
 [57 60 88]
 [17 47 63]
 [24 90 34]
 [76 70 40]
 [28 40 35]
 [92 11 65]]


In [76]:
Mmedia=np.mean(M)
print(Mmedia)

47.8


In [ ]:
#Ejercicio de funciones de agregación

In [61]:
total=np.count_nonzero(heights)
print(total)

42


In [50]:
def all_debajoMedia(L):
    media=np.mean(L)
    contador=0
    for i in L:
        if i<media:
            contador=contador+1
    return contador

In [51]:
debajoMedia=all_debajoMedia(alturas)
print(debajoMedia)

19
