Crearemos un vector de 10 elementos con valores del 1 al 10


In [1]:
import numpy as np
np.random.seed(0)

x1=np.random.randint(10,size=10)
print(x1)

[5 0 3 3 7 9 3 5 2 4]


También podemos crear una matriz. Por ejemplo creemos una matriz de 4 x 4

In [51]:
M1=np.random.randint(10,size=(4,4))
print(M1)

[[2 3 0 0]
 [6 0 6 3]
 [3 8 8 8]
 [2 3 2 0]]


O incluso un arreglo de más de dos dimensiones. Ejemplo creemos un arreglo de 3 dimensiones.

In [3]:
#Arreglo de 3 dimensiones
M3=np.random.randint(10,size=(3,3,3))
print(M3)

[[[0 3 5]
  [0 2 3]
  [8 1 3]]

 [[3 3 7]
  [0 1 9]
  [9 0 4]]

 [[7 3 2]
  [7 2 0]
  [0 4 5]]]


In [5]:
x1

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])

In [9]:
x1[5]

9

In [11]:
#Acceder a la última posición de un arreglo
x1[-1]

4

In [10]:
M1

array([[7, 6, 8, 8],
       [1, 6, 7, 7],
       [8, 1, 5, 9],
       [8, 9, 4, 3]])

In [7]:
M1[1,1]

9

In [12]:
M1[-1][-1]

3

Que se debe imprimir al imprimer el siguiente valor

In [7]:
M1[1,-1]

7

In [8]:
M1[0,0]=10
M1

array([[10,  6,  8,  8],
       [ 1,  6,  7,  7],
       [ 8,  1,  5,  9],
       [ 8,  9,  4,  3]])

In [9]:
#Asignando un valor real a un arreglo de enteros
x1[0]=5.2
x1

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])

Dado un vector V de 10 elementos arbitrarios, imprimir un subvector de V que únicamente contenta los elementos impresos de la posición 5 a la posición 8.

In [13]:
V=np.random.randint(10,size=10)
print(V)
V2=[]
for i in range(5,8):
    V2.append(V[i])
print(V2)
    

[9 4 4 6 4 4 3 4 4 8]
[4, 3, 4]


Una de las partes más interesantes de los arreglos en python, particularmente en NumPy es el uso de los slices. 

**Slicing arrays x[start:stop:step]

In [15]:
print(V[5:8])

[4 3 4]


In [22]:
x1[3:8]

array([3, 7, 9, 3, 5])

In [23]:
x1[3:8:2]

array([3, 9, 5])

In [19]:
x=np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Que se supone que debe hacer

In [25]:
x[3:8]

array([3, 4, 5, 6, 7])

In [27]:
print(x[:9])
print(x[9:])

[0 1 2 3 4 5 6 7 8]
[ 9 10 11 12 13 14 15 16 17 18 19]


In [28]:
print(x[::2])

[ 0  2  4  6  8 10 12 14 16 18]


In [29]:
print(x[3::2])

[ 3  5  7  9 11 13 15 17 19]


In [20]:
print(x[::-2])

[19 17 15 13 11  9  7  5  3  1]


In [21]:
print(x[::-1])

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [31]:
print(x[9::-2])

[9 7 5 3 1]


Veamos como utilizar slicings con arreglos de una sola dimensión

Trabajemos con el arreglo multidimensional M1

La sintaxis es similar, separando por comas el valor para cada fila

In [52]:
print(M1)

[[2 3 0 0]
 [6 0 6 3]
 [3 8 8 8]
 [2 3 2 0]]


In [53]:
M1[1:4:1,1:4:1]

array([[0, 6, 3],
       [8, 8, 8],
       [3, 2, 0]])

In [54]:
M1[::-1,::-1]

array([[0, 2, 3, 2],
       [8, 8, 8, 3],
       [3, 6, 0, 6],
       [0, 0, 3, 2]])

In [55]:
M1[:3,::2]

array([[2, 0],
       [6, 6],
       [3, 8]])

In [56]:
M1[0,0]

2

In [55]:
M1[::2,0]

array([10,  8])

In [56]:
M1[0,0]=20
print(M1[::2,::2])

[[20  8]
 [ 8  5]]


In [58]:
print(M1)

[[20  6  8  8]
 [ 1  6  7  7]
 [ 8  1  5  9]
 [ 8  9  4  3]]


In [57]:
M1_subarray=M1[:2,:2]
print(M1_subarray)

[[20  6]
 [ 1  6]]


In [59]:
M1_subarray_copy=M1_subarray.copy()
print(M1_subarray_copy)

[[20  6]
 [ 1  6]]


In [ ]:
####REDIMENSIONAR UN ARREGLO
####REDIMENSIONAR UN ARREGLO
####REDIMENSIONAR UN ARREGLO
####REDIMENSIONAR UN ARREGLO

In [60]:
#Now, veamos como utilizar el reshape
a=np.arange(9).reshape(3,3)

In [61]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
b=a.reshape(9)
print(b)

[0 1 2 3 4 5 6 7 8]


In [ ]:
####VAMOS A CONCATENAR UN PAR DE ARREGLOS Y FORMAR UNO NUEVO
####VAMOS A CONCATENAR UN PAR DE ARREGLOS Y FORMAR UNO NUEVO
####VAMOS A CONCATENAR UN PAR DE ARREGLOS Y FORMAR UNO NUEVO
####VAMOS A CONCATENAR UN PAR DE ARREGLOS Y FORMAR UNO NUEVO
####VAMOS A CONCATENAR UN PAR DE ARREGLOS Y FORMAR UNO NUEVO

In [167]:
#concatenate arrays
x=np.array([1,2,3,4,5])
y=np.array([0,2,4])
z=np.concatenate((x,y))
print(z)

[1 2 3 4 5 0 2 4]


In [153]:
myArray1=np.arange(9).reshape(3,3)
print(myArray1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [168]:
myArray2=np.concatenate((myArray1, myArray1))
print(myArray2)

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]


In [169]:
grid = np.array(([1, 2, 3],[4, 5, 6]))
print(grid)


[[1 2 3]
 [4 5 6]]


In [42]:
grid2 = np.array(([8, 8, 8],[7, 7, 7]))
grid2

array([[8, 8, 8],
       [7, 7, 7]])

In [43]:
grid3=np.random.randint(20,size=(5,3))
print(grid3)

[[ 2  3  3]
 [18 14  3]
 [17 18 14]
 [ 9  1  4]
 [10 11  8]]


In [44]:
z1=np.concatenate((grid2, grid2))
print(z1)

[[8 8 8]
 [7 7 7]
 [8 8 8]
 [7 7 7]]


In [47]:
z1=np.concatenate((grid2,grid3))
print(z1)

[[ 8  8  8]
 [ 7  7  7]
 [ 2  3  3]
 [18 14  3]
 [17 18 14]
 [ 9  1  4]
 [10 11  8]]


In [157]:
z2=np.concatenate((grid, grid2))
print(z2)

[[1 2 3]
 [4 5 6]
 [8 8 8]
 [7 7 7]]


In [171]:
myVector=np.vstack(([1,2], [3,4]))
print(myVector)

[[1 2]
 [3 4]]


In [172]:
myVector=np.hstack(([1,2],[3,4]))
print(myVector)

[1 2 3 4]


In [89]:
z3=np.vstack((grid,grid2))
print(z3)

[[1 2 3]
 [4 5 6]
 [8 8 8]
 [7 7 7]]


In [90]:
z4=np.hstack((grid,grid2))
print(z4)

[[1 2 3 8 8 8]
 [4 5 6 7 7 7]]


In [50]:
z5=np.vstack((grid2,grid3))
print(z5)

[[ 8  8  8]
 [ 7  7  7]
 [ 2  3  3]
 [18 14  3]
 [17 18 14]
 [ 9  1  4]
 [10 11  8]]


In [ ]:
####VAMOS A DIVIDIR UN ARREGLO
####VAMOS A DIVIDIR UN ARREGLO
####VAMOS A DIVIDIR UN ARREGLO
####VAMOS A DIVIDIR UN ARREGLO

In [25]:
#Opposite to concatenate, we can split
V1=np.arange(10)
z=np.split(V1,5)
print(z)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [26]:
z=np.split(V1,2)
print(z)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [174]:
print(V1)

[0 1 2 3 4 5 6 7 8 9]


In [178]:
Z=np.split(V1,[2,4,8])
print(Z)

[array([0, 1]), array([2, 3]), array([4, 5, 6, 7]), array([8, 9])]


In [28]:
M1=np.arange(9)
print(M1)

[0 1 2 3 4 5 6 7 8]


In [29]:
V1=np.split(M1,3)
print(V1)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [30]:
M1=M1.reshape(3,3)
print(M1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [31]:
s1,s2,s3=np.split(M1,3)

In [32]:
print(s1,s2,s3)

[[0 1 2]] [[3 4 5]] [[6 7 8]]


In [33]:
M2=np.arange(16).reshape(4,4)
print(M2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [37]:
M3=np.split(M2,[2,4])
print(M3[0])
print(M3[1])
print(M3[2])

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[]


 upper, lower=np.vsplit(M2,2)
print(upper)
print(lower)

In [189]:
up, down=np.vsplit(M2,2)
print(up)
print(down)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [188]:
left,right=np.hsplit(M2,2)
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [57]:
M1=np.random.randint(100,size=(4,3))
M2=np.random.randint(100,size=(4,1))
print(M1)
print(M2)

[[40 72 19]
 [95 72 26]
 [66 52 67]
 [61 14 96]]
[[ 4]
 [67]
 [11]
 [86]]


In [65]:
np.hstack((M1,M2))

array([[40, 72, 19,  4],
       [95, 72, 26, 67],
       [66, 52, 67, 11],
       [61, 14, 96, 86]])