In [4]:
import numpy as np
np.random.seed(0)

Ax=np.random.randint(20,size=16)
print(Ax)


[12 15  0  3  3  7  9 19 18  4  6 12  1  6  7 14]


In [6]:
Mx=Ax.reshape(4,4)
print(Mx)

[[12 15  0  3]
 [ 3  7  9 19]
 [18  4  6 12]
 [ 1  6  7 14]]


In [10]:
Ay=Ax[:12:-1]
print(Ay)

[14  7  6]


In [11]:
Ay=Ax[-1:12:-1]
print(Ay)

[14  7  6]


In [14]:
My=Mx[1:3:1,1:3:1]
print(My)

[[7 9]
 [4 6]]


In [22]:
V2=np.random.randint(20,size=2)
V3=np.random.randint(20,size=3).reshape((3,1))
print(V2)
print(V3)

[4 5]
[[ 6]
 [ 8]
 [17]]


In [53]:
#Concatenar
Mz=np.concatenate((My,My))
print(Mz)

[[7 9]
 [4 6]
 [7 9]
 [4 6]]


In [54]:
Mw=np.concatenate((Mz,Mz), axis=1)
print(Mw)

[[7 9 7 9]
 [4 6 4 6]
 [7 9 7 9]
 [4 6 4 6]]


In [55]:
Mz=np.vstack((My,My))
print(Mz)

[[7 9]
 [4 6]
 [7 9]
 [4 6]]


In [56]:
Mw=np.hstack((Mz,Mz))
print(Mw)

[[7 9 7 9]
 [4 6 4 6]
 [7 9 7 9]
 [4 6 4 6]]


In [57]:
#Ejercicio split
miVector=np.arange(10)
print(miVector)

[0 1 2 3 4 5 6 7 8 9]


In [67]:
miVector1,miVector2,miVector3=np.split(miVector,[5,8])
print(miVector1)
print(miVector2)
print(miVector3)

[0 1 2 3 4]
[5 6 7]
[8 9]
