In [5]:
import numpy as np


def insertion_sort(A):
    for j in range(1,len(A)):
        key=A[j]
        i=j-1
        while i>=0 and A[i]>key:
            A[i+1]=A[i]
            i=i-1
        A[i+1]=key
    return A
    
B=insertion_sort([3,1,5,4,8,9])
print(B)

[1, 3, 4, 5, 8, 9]


In [6]:
VA=np.random.randint(1,100,size=10)
print(VA)

[35 28 58 78 20 90 99  9 77 79]


In [7]:
VA_Sort=insertion_sort(VA)
print(VA_Sort)

[ 9 20 28 35 58 77 78 79 90 99]


In [16]:
VA=np.random.randint(1,100,size=10)
print(VA)

[60 12 26 40  1 82 45  8 43 35]


In [17]:
VA.sort()
print(VA)

[ 1  8 12 26 35 40 43 45 60 82]


In [19]:
VA=np.random.randint(1,100,size=10)
VASorted=np.argsort(VA)
#Imprime los índices del arreglo ordenado
print(VASorted)

[5 3 2 4 6 1 7 9 8 0]


In [21]:
print(VA[VASorted])

[13 19 31 45 47 51 70 76 87 89]


In [25]:
#Ordenar una matriz
MA=np.random.randint(100, size=(4,4))
print(MA)

[[66 61  6 40]
 [92  9 52 83]
 [73 67 55 52]
 [71 34 47 92]]


In [26]:
MA_cpy=np.copy(MA)
MA_cpy.sort()
print(MA_cpy)

[[ 6 40 61 66]
 [ 9 52 83 92]
 [52 55 67 73]
 [34 47 71 92]]


In [27]:
MA_cpy=np.copy(MA)
print(MA_cpy)

[[66 61  6 40]
 [92  9 52 83]
 [73 67 55 52]
 [71 34 47 92]]


In [30]:
#Ordenar solo por filas
MA_cpy=np.copy(MA)
np.sort(MA_cpy,axis=0)

array([[66,  9,  6, 40],
       [71, 34, 47, 52],
       [73, 61, 52, 83],
       [92, 67, 55, 92]])

In [31]:
MA_cpy=np.copy(MA)
np.sort(MA_cpy,axis=1)

array([[ 6, 40, 61, 66],
       [ 9, 52, 83, 92],
       [52, 55, 67, 73],
       [34, 47, 71, 92]])

In [32]:
#Particionando datos
VA=np.random.randint(10,size=10)
print(VA)

[5 8 1 9 1 0 9 4 0 4]


In [33]:
VA.partition(5)
print(VA)

[0 1 1 0 4 4 9 8 9 5]


In [37]:
MA=np.random.randint(1,100,size=(4,4))
print(MA)

[[47 34  9 91]
 [20  9 26 21]
 [59 78 71 86]
 [48 66 81 80]]


In [38]:
MA_Cpy=np.copy(MA)
MA_Cpy.partition(2)
print(MA_Cpy)

[[ 9 34 47 91]
 [ 9 20 21 26]
 [59 71 78 86]
 [48 66 80 81]]


In [39]:
MA_Cpy=np.copy(MA)
MA_Cpy.partition(2,axis=1)
print(MA_Cpy)


[[ 9 34 47 91]
 [ 9 20 21 26]
 [59 71 78 86]
 [48 66 80 81]]


In [49]:
###Ejercicio especial vecinos más cercanos
###Ejercicio especial vecinos más cercanos
###Ejercicio especial vecinos más cercanos
###Ejercicio especial vecinos más cercanos
###Ejercicio especial vecinos más cercanos
###Ejercicio especial vecinos más cercanos
###Ejercicio especial vecinos más cercanos
###Ejercicio especial vecinos más cercanos
